### PR TITLE
New styles

### LINKED ISSUE #71: Implements Base Responsive Framework

### PR DESCRIPTION
**Pull request by dwayhs**
Fixes #71 

The result is something like this:
screen shot 2015-07-29 at 12 22 04 am

### CODE REVIEW

**Comment by dwayhs** [comment]
This styleguide is awesome!!
http://sass-guidelin.es/

**Comment by brunotrassante** [comment]
Boohhh...Demais!

**Comment by gBritz** [comment]
Bacana.

**Comment by Alexandre-Machado** [comment]
Nice!

I have some issues to propose:
1. top bar is a bit warp
2. border of textbox don't combine

**Comment by dwayhs** [comment]
Thanks for the feedback @Alexandre-Machado 

Actually, the styles for these components aren't ready.

I merged this pull request because it's good enough, lol.

There is currently a designer working on the design for the pages. When his work is complete, we'll post the design and create tasks on waffle so people can start working on the particular components.

Hope we get a lot of contributors. :smile:

**Pull request merged**
